name: Native image pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: quarkusArtefact
          path: ./target
      - name: Compile and/or test our code
        run: mvn compile
        working-directory: .
      - name: Compile and/or test our code
        run: mvn test
