name: Native image pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - name: Compile and/or test our code
        run: mvn clean install -Pnative
      - name: Compile and/or test our code
        run: mvn test
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: quarkusArtefact
          path: ./target
